In [2]:
import pandas as pd
import numpy as np

In [3]:
train_df = pd.read_csv('../data/raw/new_data_train.csv', sep='\t')
test_df = pd.read_csv('../data/raw/new_data_test.csv', sep='\t')

In [4]:
print(train_df.shape)
train_df.head()

(9929, 23)

,Unnamed: 0,reviewID,reviewerID,restaurantID,date,rating,reviewUsefulCount,reviewContent,flagged,name,...,reviewCount,firstCount,usefulCount,coolCount,funnyCount,complimentCount,tipCount,fanCount,restaurantRating,ReviewLength
0,6010,Z_wgGcI8_Txo87Wz7CxdrQ,cM9GIlk61Qh2thLyJyxNyA,N7juvW8YoFIj7sEBzVF8GQ,9/17/2010,5,0,as new resident chicago los angeles i mission ...,1,suzie n.,...,1,0,1,2,0,0,0,0,4.0,144
1,6566,NJfQb03MSstqYagt860Oaw,SVlSPBnjCzY2Bu9n8y2C5A,o54U2VkQama8FI30qDkWvw,1/31/2008,5,0,great place rarely wait fairly easy find parki...,0,Jacqui B.,...,12,2,19,7,6,4,0,0,4.0,46
2,21349,2uao3bK9iSV4fuMwuSYCiQ,5HYWhPS3ozYifieW0lWMUw,1QKqtC4vML3QhkrSzwR_tQ,3/31/2010,5,0,back bar makes feel though transported china s...,1,Mike A.,...,6,0,7,3,2,0,0,0,3.5,18
3,10370,6mVU2JfeSbQ-5RnPm-K6eA,dgKmhiTypR34XNPrMtQyMA,4wreIFjaPMppyEnzKHbozg,4/26/2010,5,0,hands one favorite tourist restaurants city th...,0,Jen K.,...,37,2,16,3,3,1,0,1,3.5,41
4,6011,e25NUAMnVf7-t8-vBO_drA,uB3n74XHDFUKwHxfK5lDvA,N7juvW8YoFIj7sEBzVF8GQ,9/7/2010,5,0,service impeccable staff helpful owner works h...,1,Joe K.,...,3,0,2,1,0,0,0,0,4.0,40

In [5]:
train_df.columns.tolist()

['Unnamed: 0',
 'reviewID',
 'reviewerID',
 'restaurantID',
 'date',
 'rating',
 'reviewUsefulCount',
 'reviewContent',
 'flagged',
 'name',
 'location',
 'yelpJoinDate',
 'friendCount',
 'reviewCount',
 'firstCount',
 'usefulCount',
 'coolCount',
 'funnyCount',
 'complimentCount',
 'tipCount',
 'fanCount',
 'restaurantRating',
 'ReviewLength']

In [6]:
train_df['flagged'].value_counts()

flagged
0    4994
1    4935
Name: count, dtype: int64

In [7]:
train_df['flagged'].value_counts(normalize=True)

flagged
0    0.502971
1    0.497029
Name: proportion, dtype: float64

In [8]:
train_df.isnull().sum()

Unnamed: 0           0
reviewID             0
reviewerID           0
restaurantID         0
date                 0
rating               0
reviewUsefulCount    0
reviewContent        3
flagged              0
name                 0
location             1
yelpJoinDate         0
friendCount          0
reviewCount          0
firstCount           0
usefulCount          0
coolCount            0
funnyCount           0
complimentCount      0
tipCount             0
fanCount             0
restaurantRating     0
ReviewLength         0
dtype: int64

In [9]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9929 entries, 0 to 9928
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         9929 non-null   int64
 1   reviewID           9929 non-null   str
 2   reviewerID         9929 non-null   str
 3   restaurantID       9929 non-null   str
 4   date               9929 non-null   str
 5   rating             9929 non-null   int64
 6   reviewUsefulCount  9929 non-null   int64
 7   reviewContent      9926 non-null   str
 8   flagged            9929 non-null   int64
 9   name               9929 non-null   str
 10  location           9928 non-null   str
 11  yelpJoinDate       9929 non-null   str
 12  friendCount        9929 non-null   int64
 13  reviewCount        9929 non-null   int64
 14  firstCount         9929 non-null   int64
 15  usefulCount        9929 non-null   int64
 16  coolCount          9929 non-null   int64
 17  funnyCount         9929 non-null   int64
 18  complimentCount    9929 non-null   int64
 19  tipCount           9929 non-null   int64
 20  fanCount           9929 non-null   int64
 21  restaurantRating   9929 non-null   float64
 22  ReviewLength       9929 non-null   int64
dtypes: float64(1), int64(14), str(8)
memory usage: 7.1 MB

In [10]:
train_df.describe()

,Unnamed: 0,rating,reviewUsefulCount,flagged,friendCount,reviewCount,firstCount,usefulCount,coolCount,funnyCount,complimentCount,tipCount,fanCount,restaurantRating,ReviewLength
count,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000,9929.000000
mean,13951.026891,3.893041,0.496928,0.497029,31.488871,65.054487,5.726861,139.480310,97.530366,80.335683,89.967167,6.942089,3.727868,3.945664,75.271024
std,7760.870742,1.245314,1.698407,0.500016,161.622273,175.623132,34.040792,771.634041,640.034211,518.691122,827.620389,49.879472,24.049231,0.226413,69.645798
min,7.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.500000,1.000000
25%,7239.000000,3.000000,0.000000,0.000000,0.000000,3.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,30.000000
50%,13962.000000,4.000000,0.000000,0.000000,1.000000,10.000000,0.000000,5.000000,1.000000,1.000000,0.000000,0.000000,0.000000,4.000000,54.000000
75%,20878.000000,5.000000,0.000000,1.000000,13.000000,42.000000,1.000000,35.000000,13.000000,12.000000,4.000000,0.000000,1.000000,4.000000,99.000000
max,26953.000000,5.000000,49.000000,1.000000,3945.000000,2162.000000,834.000000,19452.000000,17199.000000,14285.000000,31111.000000,1710.000000,503.000000,4.500000,593.000000

In [11]:
train_df.groupby('flagged').mean(numeric_only=True)

,Unnamed: 0,rating,reviewUsefulCount,friendCount,reviewCount,firstCount,usefulCount,coolCount,funnyCount,complimentCount,tipCount,fanCount,restaurantRating,ReviewLength
flagged,,,,,,,,,,,,,,
0,12929.991990,3.968763,0.987986,60.059872,122.290549,11.143172,274.110933,192.598919,158.620144,178.380857,13.564277,7.335803,3.958450,89.287946
1,14984.268693,3.816413,0.000000,2.576292,7.134144,0.245795,3.240122,1.325228,1.115299,0.496454,0.240729,0.076798,3.932725,61.086525

EDA

In [12]:
numeric_cols = train_df.select_dtypes(include=['int64', 'float64'])

correlation = numeric_cols.corr()

correlation['flagged'].sort_values(ascending=False)

flagged              1.000000
Unnamed: 0           0.132353
restaurantRating    -0.056811
rating              -0.061171
complimentCount     -0.107471
tipCount            -0.133562
coolCount           -0.149429
fanCount            -0.150925
funnyCount          -0.151834
firstCount          -0.160069
usefulCount         -0.175523
friendCount         -0.177839
ReviewLength        -0.202470
reviewUsefulCount   -0.290866
reviewCount         -0.327862
Name: flagged, dtype: float64

In [13]:
train_df.duplicated().sum()

np.int64(0)

In [14]:
train_df.groupby('flagged')['ReviewLength'].mean()

flagged
0    89.287946
1    61.086525
Name: ReviewLength, dtype: float64

In [15]:
train_df.groupby('flagged')['rating'].mean()

flagged
0    3.968763
1    3.816413
Name: rating, dtype: float64

In [16]:
social_features = [
    'friendCount',
    'reviewCount',
    'usefulCount',
    'coolCount',
    'funnyCount',
    'complimentCount',
    'fanCount'
]

train_df.groupby('flagged')[social_features].mean()

,friendCount,reviewCount,usefulCount,coolCount,funnyCount,complimentCount,fanCount
flagged,,,,,,,
0,60.059872,122.290549,274.110933,192.598919,158.620144,178.380857,7.335803
1,2.576292,7.134144,3.240122,1.325228,1.115299,0.496454,0.076798

Data Cleaning

In [17]:
train_df = train_df.drop(columns=['Unnamed: 0'])
test_df = test_df.drop(columns=['Unnamed: 0'])

In [18]:
train_df['reviewContent'] = train_df['reviewContent'].fillna('')
test_df['reviewContent'] = test_df['reviewContent'].fillna('')

train_df['location'] = train_df['location'].fillna('Unknown')
test_df['location'] = test_df['location'].fillna('Unknown')

In [20]:
train_df['yelpJoinDate'].head(10)

0   2009-07-01
1   2008-01-01
2   2010-03-01
3   2010-03-01
4   2009-12-01
5   2008-09-01
6   2010-08-01
7   2007-11-01
8   2009-08-01
9   2010-07-01
Name: yelpJoinDate, dtype: datetime64[us]

In [21]:
train_df['date'] = pd.to_datetime(
    train_df['date'],
    format='%m/%d/%Y'
)

train_df['yelpJoinDate'] = pd.to_datetime(
    train_df['yelpJoinDate'],
    format='%Y-%m-%d'
)

test_df['date'] = pd.to_datetime(
    test_df['date'],
    format='%m/%d/%Y'
)

test_df['yelpJoinDate'] = pd.to_datetime(
    test_df['yelpJoinDate'],
    format='%Y-%m-%d'
)

In [22]:
train_df['reviewContent'] = (
    train_df['reviewContent']
    .str.lower()
    .str.strip()
)

test_df['reviewContent'] = (
    test_df['reviewContent']
    .str.lower()
    .str.strip()
)

In [23]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9929 entries, 0 to 9928
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   reviewID           9929 non-null   str
 1   reviewerID         9929 non-null   str
 2   restaurantID       9929 non-null   str
 3   date               9929 non-null   datetime64[us]
 4   rating             9929 non-null   int64
 5   reviewUsefulCount  9929 non-null   int64
 6   reviewContent      9929 non-null   str
 7   flagged            9929 non-null   int64
 8   name               9929 non-null   str
 9   location           9929 non-null   str
 10  yelpJoinDate       9929 non-null   datetime64[us]
 11  friendCount        9929 non-null   int64
 12  reviewCount        9929 non-null   int64
 13  firstCount         9929 non-null   int64
 14  usefulCount        9929 non-null   int64
 15  coolCount          9929 non-null   int64
 16  funnyCount         9929 non-null   int64
 17  complimentCount    9929 non-null   int64
 18  tipCount           9929 non-null   int64
 19  fanCount           9929 non-null   int64
 20  restaurantRating   9929 non-null   float64
 21  ReviewLength       9929 non-null   int64
dtypes: datetime64[us](2), float64(1), int64(13), str(6)
memory usage: 6.8 MB

In [24]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2483 entries, 0 to 2482
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   reviewID           2483 non-null   str
 1   reviewerID         2483 non-null   str
 2   restaurantID       2483 non-null   str
 3   date               2483 non-null   datetime64[us]
 4   rating             2483 non-null   int64
 5   reviewUsefulCount  2483 non-null   int64
 6   reviewContent      2483 non-null   str
 7   flagged            2483 non-null   int64
 8   name               2483 non-null   str
 9   location           2483 non-null   str
 10  yelpJoinDate       2483 non-null   datetime64[us]
 11  friendCount        2483 non-null   int64
 12  reviewCount        2483 non-null   int64
 13  firstCount         2483 non-null   int64
 14  usefulCount        2483 non-null   int64
 15  coolCount          2483 non-null   int64
 16  funnyCount         2483 non-null   int64
 17  complimentCount    2483 non-null   int64
 18  tipCount           2483 non-null   int64
 19  fanCount           2483 non-null   int64
 20  restaurantRating   2483 non-null   float64
 21  ReviewLength       2483 non-null   int64
dtypes: datetime64[us](2), float64(1), int64(13), str(6)
memory usage: 1.7 MB

In [25]:
train_df.to_csv(
    '../data/cleaned/train_cleaned.csv',
    index=False
)

test_df.to_csv(
    '../data/cleaned/test_cleaned.csv',
    index=False
)

print("Cleaned datasets saved successfully.")

Cleaned datasets saved successfully.